from typing import List, Union

from transformers import MBartTokenizer
from ftfy import fix_text

from amr_bart.amr_bart.linearization import escape_xml

# Idea Tim: remove outlier from special tokens, so that these outliers will be automatically tokenized
# This may make it difficult to postprocess the trees, but we can try!
tokens_to_add = ['</rel>',
                 '</tree>',
                 '<negation/>',
                 '<rel>',
                 '<reltype value=":ARG0"/>',
                 '<reltype value=":ARG0-of"/>',
                 '<reltype value=":ARG1"/>',
                 '<reltype value=":ARG1-of"/>',
                 '<reltype value=":ARG2"/>',
                 '<reltype value=":ARG2-of"/>',
                 '<reltype value=":ARG3"/>',
                 '<reltype value=":ARG3-of"/>',
                 '<reltype value=":ARG4"/>',
                 '<reltype value=":ARG4-of"/>',
                 '<reltype value=":ARG5"/>',
                 '<reltype value=":ARG5-of"/>',
                 '<reltype value=":ARG6"/>',
                 '<reltype value=":ARG6-of"/>',
                 '<reltype value=":ARG7"/>',
                 '<reltype value=":ARG7-of"/>',
                 '<reltype value=":ARG8"/>',
                 '<reltype value=":ARG9"/>',
                 '<reltype value=":accompanier"/>',
                 '<reltype value=":accompanier-of"/>',
                 '<reltype value=":age"/>',
                 '<reltype value=":age-of"/>',
                 '<reltype value=":beneficiary"/>',
                 '<reltype value=":beneficiary-of"/>',
                 '<reltype value=":calendar"/>',
                 '<reltype value=":century"/>',
                 '<reltype value=":concession"/>',
                 '<reltype value=":concession-of"/>',
                 '<reltype value=":condition"/>',
                 '<reltype value=":condition-of"/>',
                 '<reltype value=":conj-as-if"/>',
                 '<reltype value=":consist-of"/>',
                 '<reltype value=":day"/>',
                 '<reltype value=":dayperiod"/>',
                 '<reltype value=":decade"/>',
                 '<reltype value=":degree"/>',
                 '<reltype value=":degree-of"/>',
                 '<reltype value=":destination"/>',
                 '<reltype value=":destination-of"/>',
                 '<reltype value=":direction"/>',
                 '<reltype value=":direction-of"/>',
                 '<reltype value=":domain"/>',
                 '<reltype value=":duration"/>',
                 '<reltype value=":duration-of"/>',
                 '<reltype value=":era"/>',
                 '<reltype value=":example"/>',
                 '<reltype value=":example-of"/>',
                 '<reltype value=":extent"/>',
                 '<reltype value=":extent-of"/>',
                 '<reltype value=":frequency"/>',
                 '<reltype value=":frequency-of"/>',
                 '<reltype value=":instrument"/>',
                 '<reltype value=":instrument-of"/>',
                 '<reltype value=":li"/>',
                 '<reltype value=":location"/>',
                 '<reltype value=":location-of"/>',
                 '<reltype value=":manner"/>',
                 '<reltype value=":manner-of"/>',
                 '<reltype value=":medium"/>',
                 '<reltype value=":medium-of"/>',
                 '<reltype value=":mod"/>',
                 '<reltype value=":mode"/>',
                 '<reltype value=":month"/>',
                 '<reltype value=":name"/>',
                 '<reltype value=":name-of"/>',
                 '<reltype value=":op1"/>',
                 '<reltype value=":op1-of"/>',
                 '<reltype value=":op10"/>',
                 '<reltype value=":op11"/>',
                 '<reltype value=":op12"/>',
                 '<reltype value=":op13"/>',
                 '<reltype value=":op14"/>',
                 '<reltype value=":op15"/>',
                 '<reltype value=":op16"/>',
                 '<reltype value=":op17"/>',
                 '<reltype value=":op18"/>',
                 '<reltype value=":op19"/>',
                 '<reltype value=":op2"/>',
                 '<reltype value=":op20"/>',
                 '<reltype value=":op21"/>',
                 '<reltype value=":op22"/>',
                 '<reltype value=":op23"/>',
                 '<reltype value=":op24"/>',
                 '<reltype value=":op3"/>',
                 '<reltype value=":op4"/>',
                 '<reltype value=":op5"/>',
                 '<reltype value=":op6"/>',
                 '<reltype value=":op7"/>',
                 '<reltype value=":op8"/>',
                 '<reltype value=":op9"/>',
                 '<reltype value=":ord"/>',
                 '<reltype value=":ord-of"/>',
                 '<reltype value=":part"/>',
                 '<reltype value=":part-of"/>',
                 '<reltype value=":path"/>',
                 '<reltype value=":path-of"/>',
                 '<reltype value=":polarity"/>',
                 '<reltype value=":polarity-of"/>',
                 '<reltype value=":polite"/>',
                 '<reltype value=":poss"/>',
                 '<reltype value=":poss-of"/>',
                 '<reltype value=":prep-against"/>',
                 '<reltype value=":prep-along-with"/>',
                 '<reltype value=":prep-amid"/>',
                 '<reltype value=":prep-among"/>',
                 '<reltype value=":prep-as"/>',
                 '<reltype value=":prep-at"/>',
                 '<reltype value=":prep-by"/>',
                 '<reltype value=":prep-for"/>',
                 '<reltype value=":prep-from"/>',
                 '<reltype value=":prep-in"/>',
                 '<reltype value=":prep-in-addition-to"/>',
                 '<reltype value=":prep-into"/>',
                 '<reltype value=":prep-on"/>',
                 '<reltype value=":prep-on-behalf-of"/>',
                 '<reltype value=":prep-out-of"/>',
                 '<reltype value=":prep-to"/>',
                 '<reltype value=":prep-toward"/>',
                 '<reltype value=":prep-under"/>',
                 '<reltype value=":prep-with"/>',
                 '<reltype value=":prep-without"/>',
                 '<reltype value=":purpose"/>',
                 '<reltype value=":purpose-of"/>',
                 '<reltype value=":quant"/>',
                 '<reltype value=":quant-of"/>',
                 '<reltype value=":quarter"/>',
                 '<reltype value=":range"/>',
                 '<reltype value=":scale"/>',
                 '<reltype value=":season"/>',
                 '<reltype value=":snt1"/>',
                 '<reltype value=":snt10"/>',
                 '<reltype value=":snt11"/>',
                 '<reltype value=":snt2"/>',
                 '<reltype value=":snt3"/>',
                 '<reltype value=":snt4"/>',
                 '<reltype value=":snt5"/>',
                 '<reltype value=":snt6"/>',
                 '<reltype value=":snt7"/>',
                 '<reltype value=":snt8"/>',
                 '<reltype value=":snt9"/>',
                 '<reltype value=":source"/>',
                 '<reltype value=":source-of"/>',
                 '<reltype value=":subevent"/>',
                 '<reltype value=":subevent-of"/>',
                 '<reltype value=":subset"/>',
                 '<reltype value=":subset-of"/>',
                 '<reltype value=":time"/>',
                 '<reltype value=":time-of"/>',
                 '<reltype value=":timezone"/>',
                 '<reltype value=":topic"/>',
                 '<reltype value=":topic-of"/>',
                 '<reltype value=":unit"/>',
                 '<reltype value=":value"/>',
                 '<reltype value=":value-of"/>',
                 '<reltype value=":weekday"/>',
                 '<reltype value=":year"/>',
                 '<reltype value=":year2"/>',
                 '<sense_id value="00"/>',
                 '<sense_id value="01"/>',
                 '<sense_id value="02"/>',
                 '<sense_id value="03"/>',
                 '<sense_id value="04"/>',
                 '<sense_id value="05"/>',
                 '<sense_id value="06"/>',
                 '<sense_id value="07"/>',
                 '<sense_id value="08"/>',
                 '<sense_id value="09"/>',
                 '<sense_id value="10"/>',
                 '<sense_id value="101"/>',
                 '<sense_id value="11"/>',
                 '<sense_id value="12"/>',
                 '<sense_id value="13"/>',
                 '<sense_id value="14"/>',
                 '<sense_id value="15"/>',
                 '<sense_id value="16"/>',
                 '<sense_id value="17"/>',
                 '<sense_id value="18"/>',
                 '<sense_id value="19"/>',
                 '<sense_id value="20"/>',
                 '<sense_id value="21"/>',
                 '<sense_id value="22"/>',
                 '<sense_id value="23"/>',
                 '<sense_id value="24"/>',
                 '<sense_id value="25"/>',
                 '<sense_id value="26"/>',
                 '<sense_id value="27"/>',
                 '<sense_id value="28"/>',
                 '<sense_id value="29"/>',
                 '<sense_id value="30"/>',
                 '<sense_id value="31"/>',
                 '<sense_id value="32"/>',
                 '<sense_id value="33"/>',
                 '<sense_id value="34"/>',
                 '<sense_id value="35"/>',
                 '<sense_id value="36"/>',
                 '<sense_id value="38"/>',
                 '<sense_id value="91"/>',
                 '<sense_id value="92"/>',
                 '<sense_id value="NO"/>',
                 '<termid value="R0"/>',
                 '<termid value="R1"/>',
                 '<termid value="R10"/>',
                 '<termid value="R100"/>',
                 '<termid value="R101"/>',
                 '<termid value="R102"/>',
                 '<termid value="R103"/>',
                 '<termid value="R104"/>',
                 '<termid value="R105"/>',
                 '<termid value="R106"/>',
                 '<termid value="R107"/>',
                 '<termid value="R108"/>',
                 '<termid value="R109"/>',
                 '<termid value="R11"/>',
                 '<termid value="R110"/>',
                 '<termid value="R111"/>',
                 '<termid value="R112"/>',
                 '<termid value="R113"/>',
                 '<termid value="R114"/>',
                 '<termid value="R115"/>',
                 '<termid value="R116"/>',
                 '<termid value="R117"/>',
                 '<termid value="R118"/>',
                 '<termid value="R119"/>',
                 '<termid value="R12"/>',
                 '<termid value="R120"/>',
                 '<termid value="R121"/>',
                 '<termid value="R122"/>',
                 '<termid value="R123"/>',
                 '<termid value="R124"/>',
                 '<termid value="R125"/>',
                 '<termid value="R126"/>',
                 '<termid value="R127"/>',
                 '<termid value="R128"/>',
                 '<termid value="R129"/>',
                 '<termid value="R13"/>',
                 '<termid value="R130"/>',
                 '<termid value="R131"/>',
                 '<termid value="R132"/>',
                 '<termid value="R133"/>',
                 '<termid value="R134"/>',
                 '<termid value="R135"/>',
                 '<termid value="R136"/>',
                 '<termid value="R137"/>',
                 '<termid value="R138"/>',
                 '<termid value="R139"/>',
                 '<termid value="R14"/>',
                 '<termid value="R140"/>',
                 '<termid value="R141"/>',
                 '<termid value="R15"/>',
                 '<termid value="R16"/>',
                 '<termid value="R17"/>',
                 '<termid value="R18"/>',
                 '<termid value="R19"/>',
                 '<termid value="R2"/>',
                 '<termid value="R20"/>',
                 '<termid value="R21"/>',
                 '<termid value="R22"/>',
                 '<termid value="R23"/>',
                 '<termid value="R24"/>',
                 '<termid value="R25"/>',
                 '<termid value="R26"/>',
                 '<termid value="R27"/>',
                 '<termid value="R28"/>',
                 '<termid value="R29"/>',
                 '<termid value="R3"/>',
                 '<termid value="R30"/>',
                 '<termid value="R31"/>',
                 '<termid value="R32"/>',
                 '<termid value="R33"/>',
                 '<termid value="R34"/>',
                 '<termid value="R35"/>',
                 '<termid value="R36"/>',
                 '<termid value="R37"/>',
                 '<termid value="R38"/>',
                 '<termid value="R39"/>',
                 '<termid value="R4"/>',
                 '<termid value="R40"/>',
                 '<termid value="R41"/>',
                 '<termid value="R42"/>',
                 '<termid value="R43"/>',
                 '<termid value="R44"/>',
                 '<termid value="R45"/>',
                 '<termid value="R46"/>',
                 '<termid value="R47"/>',
                 '<termid value="R48"/>',
                 '<termid value="R49"/>',
                 '<termid value="R5"/>',
                 '<termid value="R50"/>',
                 '<termid value="R51"/>',
                 '<termid value="R52"/>',
                 '<termid value="R53"/>',
                 '<termid value="R54"/>',
                 '<termid value="R55"/>',
                 '<termid value="R56"/>',
                 '<termid value="R57"/>',
                 '<termid value="R58"/>',
                 '<termid value="R59"/>',
                 '<termid value="R6"/>',
                 '<termid value="R60"/>',
                 '<termid value="R61"/>',
                 '<termid value="R62"/>',
                 '<termid value="R63"/>',
                 '<termid value="R64"/>',
                 '<termid value="R65"/>',
                 '<termid value="R66"/>',
                 '<termid value="R67"/>',
                 '<termid value="R68"/>',
                 '<termid value="R69"/>',
                 '<termid value="R7"/>',
                 '<termid value="R70"/>',
                 '<termid value="R71"/>',
                 '<termid value="R72"/>',
                 '<termid value="R73"/>',
                 '<termid value="R74"/>',
                 '<termid value="R75"/>',
                 '<termid value="R76"/>',
                 '<termid value="R77"/>',
                 '<termid value="R78"/>',
                 '<termid value="R79"/>',
                 '<termid value="R8"/>',
                 '<termid value="R80"/>',
                 '<termid value="R81"/>',
                 '<termid value="R82"/>',
                 '<termid value="R83"/>',
                 '<termid value="R84"/>',
                 '<termid value="R85"/>',
                 '<termid value="R86"/>',
                 '<termid value="R87"/>',
                 '<termid value="R88"/>',
                 '<termid value="R89"/>',
                 '<termid value="R9"/>',
                 '<termid value="R90"/>',
                 '<termid value="R91"/>',
                 '<termid value="R92"/>',
                 '<termid value="R93"/>',
                 '<termid value="R94"/>',
                 '<termid value="R95"/>',
                 '<termid value="R96"/>',
                 '<termid value="R97"/>',
                 '<termid value="R98"/>',
                 '<termid value="R99"/>',
                 '<termref value="R0"/>',
                 '<termref value="R1"/>',
                 '<termref value="R10"/>',
                 '<termref value="R101"/>',
                 '<termref value="R105"/>',
                 '<termref value="R106"/>',
                 '<termref value="R109"/>',
                 '<termref value="R11"/>',
                 '<termref value="R110"/>',
                 '<termref value="R117"/>',
                 '<termref value="R118"/>',
                 '<termref value="R119"/>',
                 '<termref value="R12"/>',
                 '<termref value="R13"/>',
                 '<termref value="R133"/>',
                 '<termref value="R134"/>',
                 '<termref value="R14"/>',
                 '<termref value="R15"/>',
                 '<termref value="R16"/>',
                 '<termref value="R17"/>',
                 '<termref value="R18"/>',
                 '<termref value="R19"/>',
                 '<termref value="R2"/>',
                 '<termref value="R20"/>',
                 '<termref value="R21"/>',
                 '<termref value="R22"/>',
                 '<termref value="R23"/>',
                 '<termref value="R24"/>',
                 '<termref value="R25"/>',
                 '<termref value="R26"/>',
                 '<termref value="R27"/>',
                 '<termref value="R28"/>',
                 '<termref value="R29"/>',
                 '<termref value="R3"/>',
                 '<termref value="R30"/>',
                 '<termref value="R31"/>',
                 '<termref value="R32"/>',
                 '<termref value="R33"/>',
                 '<termref value="R34"/>',
                 '<termref value="R35"/>',
                 '<termref value="R36"/>',
                 '<termref value="R37"/>',
                 '<termref value="R38"/>',
                 '<termref value="R39"/>',
                 '<termref value="R4"/>',
                 '<termref value="R40"/>',
                 '<termref value="R41"/>',
                 '<termref value="R42"/>',
                 '<termref value="R43"/>',
                 '<termref value="R44"/>',
                 '<termref value="R45"/>',
                 '<termref value="R46"/>',
                 '<termref value="R47"/>',
                 '<termref value="R48"/>',
                 '<termref value="R49"/>',
                 '<termref value="R5"/>',
                 '<termref value="R50"/>',
                 '<termref value="R51"/>',
                 '<termref value="R52"/>',
                 '<termref value="R53"/>',
                 '<termref value="R54"/>',
                 '<termref value="R55"/>',
                 '<termref value="R56"/>',
                 '<termref value="R57"/>',
                 '<termref value="R58"/>',
                 '<termref value="R59"/>',
                 '<termref value="R6"/>',
                 '<termref value="R60"/>',
                 '<termref value="R62"/>',
                 '<termref value="R63"/>',
                 '<termref value="R64"/>',
                 '<termref value="R65"/>',
                 '<termref value="R66"/>',
                 '<termref value="R67"/>',
                 '<termref value="R68"/>',
                 '<termref value="R69"/>',
                 '<termref value="R7"/>',
                 '<termref value="R71"/>',
                 '<termref value="R72"/>',
                 '<termref value="R73"/>',
                 '<termref value="R74"/>',
                 '<termref value="R75"/>',
                 '<termref value="R76"/>',
                 '<termref value="R77"/>',
                 '<termref value="R78"/>',
                 '<termref value="R79"/>',
                 '<termref value="R8"/>',
                 '<termref value="R80"/>',
                 '<termref value="R81"/>',
                 '<termref value="R85"/>',
                 '<termref value="R89"/>',
                 '<termref value="R9"/>',
                 '<termref value="R91"/>',
                 '<termref value="R96"/>',
                 '<termref value="R97"/>',
                 '<termref value="R99"/>',
                 '<tree type="linearized_xml">'
]


def clean_up_tokenization(out_string: str) -> str:
    """
    Clean up a list of simple English tokenization artifacts like spaces before punctuations and abbreviated forms.

    Args:
        out_string (`str`): The text to clean up.

    Returns:
        `str`: The cleaned-up string.
    """
    out_string = (
        out_string.replace(" .", ".")
        .replace(" ?", "?")
        .replace(" !", "!")
        .replace(" ,", ",")
        .replace(" ' ", "'")
        .replace(" n't", "n't")
        .replace(" 'm", "'m")
        .replace(" 's", "'s")
        .replace(" 've", "'ve")
        .replace(" 're", "'re")
    )
    return out_string


class AMRMBartTokenizer(MBartTokenizer):
    # TODO: when encoding, make sure we account for escaped characters. So first unescape, i.e.,
    #  linearized = fix_text(unescape_xml(linearizer.linearized))
    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        inst = super().from_pretrained(*args, **kwargs)
        voc = set(inst.get_vocab().keys())
        # Only add tokens that are not in here yet.
        tokens_to_add.extend(["amr_XX"])
        new_tokens = set(tokens_to_add) - voc
        if new_tokens:
            inst.add_tokens(list(sorted(new_tokens)))
            print(f"Added {len(new_tokens):,} new tokens!")

        return inst

    def decode_and_escape(self, token_ids: List[int]):
        filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=True)
        filtered_tokens = [token if token in tokens_to_add else escape_xml(fix_text(token)) for token in
                           filtered_tokens]

        # To avoid mixing byte-level and unicode for byte-level BPT
        # we need to build string separately for added tokens and byte-level tokens
        # cf. https://github.com/huggingface/transformers/issues/1133
        sub_texts = []
        current_sub_text = []
        for token in filtered_tokens:
            if token in tokens_to_add:
                if current_sub_text:
                    sub_texts.append(self.convert_tokens_to_string(current_sub_text))
                    current_sub_text = []
                sub_texts.append(token)
            else:
                current_sub_text.append(token)
        if current_sub_text:
            sub_texts.append(self.convert_tokens_to_string(current_sub_text))

        text = " ".join(sub_texts)
        text = clean_up_tokenization(text)
        return text
